/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lin_jdroid_MyActivity */

#ifndef _Included_com_example_lin_jdroid_MyActivity
#define _Included_com_example_lin_jdroid_MyActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lin_jdroid_MyActivity
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lin_jdroid_MyActivity_getStringFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
